version: '3.7'

services:
  jenkins:
    image: liofal/jenkins
    container_name: jenkins
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080/tcp
      - 50000:50000/tcp
    env_file: 
        - .env
        # - ../global.env    
    hostname: liofal.synology.me
    volumes:
      - /volume1/docker/jenkins/config:/var/jenkins_home
      - /volume1/twitch:/downloads/twitch
      - /volume1/sonarr:/downloads/sonarr
      - /volume1/radarr:/downloads/radarr
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: json-file
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      jenkins:
  
networks:
  jenkins:
    name: jenkins
